### ISSUE TITLE
Limits the amount of light emitted by the screen.

### ISSUE THREAD

**Issue by weepy** [Organic-Basics/ob-low-impact-website#12]
Hiya - great site! 

Can you tell me what you mean by "Limits the amount of light emitted by the screen." ? How does that work ? 

Jonah

**Comment by jepster-dk** [comment]
Hi Jonah

One way to read this manifesto point is that a low-impact website should use whatever means necessary to use darker colors. It could however also mean that a site urges users to turn down the light on their screen.

As with other things in the manifesto, there is some wiggle room to adapt this to each individual site. The Organic Basics brand is very reliant on a lot of white backgrounds, so we've compromised a bit by using a slight yellow color and a darker grey than we're usually using. 

It's incredibly difficult to quantify the effect this has on the amount of CO2e emitted by a website, but it's something we should be aware of none-the-less.

**Comment by weepy** [comment]
That makes sense. Although it's actually only relevant on OLED screens since LED has a backlight.
