### ISSUE TITLE
Size and performance

### ISSUE THREAD

**Issue by YamiteruXYZ** [Organic-Basics/ob-low-impact-website#17]
The site loads around 5mb of data over 95 requests. This years average is 2.07MB. Transferring all this data costs money and most importantly our planet.

Also there is almost 1mb of JS scripts (uncompressed) and that's A LOT! I have a fairly good pc (6 core, 16gb ram) but scripting takes 1s from 5s test. I didn't test on a phone but I'm sure that this drains battery a lot which draws the site very ineffective in saving power.

**Comment by jepster-dk** [comment]
Hey there! 

Thanks for submitting an issue. We love getting feedback! 

Could you give me some more background on how specifically you ran these tests?
Are you using Chrome? Firefox? Lighthouse? 

It'd also be great to hear which URLs you're testing. 

Is it just the root URL https://lowimpact.organicbasics.com ? Or one of the collection pages like https://lowimpact.organicbasics.com/collections/all-womens-products ?

**Comment by YamiteruXYZ** [comment]
Hi! 

I've used Lighthouse in Google Chrome and I tested https://organicbasics.com/collections/all-womens-products.

The https://lowimpact.organicbasics.com seems to adhere to the rules you made.

Now the site is loading 4.5MB over a whopping 279 requests and it takes 2.75s for DOMContentLoaded to finish. It seems that you're preloading all thumbnail images. I see why you'd want to do it, but does an average user really need to have all those <1Kb images preloaded? I don't think so.

I also see you're using jQuery. Generally speaking you don't need jQuery nowadays, because modern vanilla JS is very powerful. 

Let's look at the code coverage!

![image](https://user-images.githubusercontent.com/34185465/96849902-7ce41f00-1456-11eb-950a-7522da5cfe5c.png)

Ok so it seems like a user needs to load 1.7MB of scripts and styles, parse them (which takes a lot of time, especially with scripts) and then throw away 65% (1.1MB) of them. I wouldn't call this efficient or power saving. 

I highly recommend reading through this https://web.dev/fast/.

**Comment by jepster-dk** [comment]
Thanks for this in-depth analysis, @YamiteruXYZ. 

We're actually currently working on rebuilding our main site (www.organicbasics.com), because I completely agree with all your above conclusions. 

I'll close this issue for now, since it doesn't pertain to the low impact website, which this repository is the home for.

**Comment by YamiteruXYZ** [comment]
That's wicked! Good luck :)
