### ISSUE TITLE
Exposed Contentful Access Token

### ISSUE THREAD

**Issue by KasperAndersson** [Organic-Basics/ob-low-impact-website#8]
Might be wrong, but haven't you exposed your access token?
https://github.com/Organic-Basics/ob-low-impact-website/blob/develop/.contentful.json

**Comment by jepster-dk** [comment]
Hi Kasper! 

Thanks a lot for creating this issue! The Contentful key does not expose any confidential information per se, and is usually exposed somehow in the frontend of many apps. However, it's much better practice to not expose it directly on Github, so I've gone ahead and created a new key that is now secret as per commit e85461316daad6afa9890adfe4385b83c637edb2 . 

Thanks again for keeping us on our toes 🦶
